version: "2"
services:
  postgres:
    image: postgres:9.6.1
    ports:
    - "0.0.0.0:5432:5432"
    volumes:
    - data:/var/lib/postgresql/data
    - "./dbscripts/init_postgres_database.sql:/docker-entrypoint-initdb.d/init_postgres_database.sql"
    environment:
    - POSTGRES_PASSWORD=secret
    - POSTGRES_USER=postgres
    - POSTGRES_DB=dhx_adapter

  dhx-adapter:
    image: tomcat:8.5
    ports:
    - "0.0.0.0:8443:8443"
    - "0.0.0.0:8080:8080"
    - "0.0.0.0:9010:9010"
    - "0.0.0.0:5005:5005"
    volumes:
    - "C:/Users/kaarelr/Desktop/Trash/RIA/DHX:/usr/local/tomcat/webapps/conf/ssl"
    - "./dhx-adapter-server/target/dhx-adapter-server.war:/usr/local/tomcat/webapps/dhx-adapter-server.war"
    - "./src/main/resources/conf/docker/dhx-application.properties:/conf/dhx-application.properties"
    - "./src/main/resources/conf/docker/catalina.properties:/usr/local/tomcat/conf/catalina.properties"
    - "./src/main/resources/conf/docker/context.xml:/usr/local/tomcat/conf/context.xml"
    environment:
      CATALINA_OPTS: >
        -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
        -Dcom.sun.management.jmxremote.rmi.port=9010
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.port=9010
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.local.only=false
        -Djava.rmi.server.hostname=192.168.83.94
        -Djava.security.policy=/root/jstatd.all.policy
        -Djava.net.preferIPv4Stack=true

volumes:
  data: